bir/urls.py
from django.urls import path
from .views import HomeView, AboutView, ServicesView, GalleryView, ContactView

app_name = 'bir'

urlpatterns = [
    path('', HomeView.as_view(), name="home_page"),
    path('about-us/', AboutView.as_view(), name="about_page"),
    path('services/', ServicesView.as_view(), name="services_page"),
    path('gallery/', GalleryView.as_view(), name='gallery_page'),
    path('contact/', ContactView.as_view(), name='contact_page'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bir.urls'))
]

bir/models.py
from django.db import models

class Post(models.Model):
    nomi = models.CharField(max_length=255)
    text = models.TextField(max_length=1000)


    def __str__(self):
        return self.nomi

bir/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

def home_page(request):
    return render(request, 'index.html',)

class HomeView(TemplateView):
    template_name = 'index.html'
class AboutView(TemplateView):
    template_name = 'about-us.html'
class ServicesView(TemplateView):
    template_name = 'services.html'
class GalleryView(TemplateView):
    template_name = 'gallery.html'
class ContactView(TemplateView):
    template_name = 'contact.html'

templates/about-us.html
{% load static %}
<!DOCTYPE html>
<html lang="en-US">
 <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Free responsive business website template</title>
    <link rel="stylesheet" href="{% static 'css/components.css' %}">
    <link rel="stylesheet" href="{% static 'css/icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsee.css' %}">
    <link rel="stylesheet" href="{% static 'owl-carousel/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'owl-carousel/owl.theme.css' %}">
    <!-- CUSTOM STYLE -->      
    <link rel="stylesheet" href="{% static 'css/template-style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Barlow:100,300,400,700,800&amp;subset=latin-ext" rel="stylesheet">  
    <script type="text/javascript" src="{% static 'js/jquery-1.8.3.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>    
 </head>

 <!--
    You can change the color scheme of the page. Just change the class of the <body> tag. 
    You can use this class: "primary-color-white", "primary-color-red", "primary-color-orange", "primary-color-blue", "primary-color-aqua", "primary-color-dark" 
    -->
    
    <!--
    Each element is able to have its own background or text color. Just change the class of the element.  
    You can use this class: 
    "background-white", "background-red", "background-orange", "background-blue", "background-aqua", "background-primary" 
    "text-white", "text-red", "text-orange", "text-blue", "text-aqua", "text-primary"
    -->

   <body class="size-1520 primary-color-red background-dark">
      <!-- HEADER -->
      <header class="grid">
        <!-- Top Navigation -->
        <nav class="s-12 grid background-none background-primary-hightlight">
           <!-- logo -->
           <a href="/" class="m-12 l-3 padding-2x logo">
              <img src="{% static 'img/logo.svg' %}">
           </a>
           <div class="top-nav s-12 l-9"> 
              <ul class="top-ul right chevron">
                <li><a href="{% url 'bir:home_page' %}">Home</a></li>
                <li><a href="{% url 'bir:about_page' %}">About Us</a></li>
                <li><a href="{% url 'bir:services_page' %}">Services</a></li>
                <li><a href="{% url 'bir:gallery_page' %}">Gallery</a></li>
                <li><a href="{% url 'bir:contact_page' %}">Contact</a></li>
              </ul>
           </div>
        </nav>
      </header>
      
      <!-- MAIN -->
      <main role="main">
        <!-- TOP SECTION -->
        <header class="grid">
        	<div class="s-12 padding-2x">
            <h1 class="text-strong text-white text-center center text-size-60 text-uppercase margin-bottom-20">About Us</h1>
            <p class="text-size-20 text-white text-center center text-uppercase">Con nonummy sem integer interdum volutpat dis eget eligendi aliquip dolorum magnam. Iriure duis autem vel<br> eum dolor in hendrerit in vulputate velit esse molestie consequat.</p>
          </div>
        </header>
  
        
        <!-- SECTION 1 -->
        <section class="grid">        
          <div class="m-12 l-6 padding-2x background-white">
            <h2 class="text-dark">Nonummy nibh euismod tincidunt ut laoreet</h2>
            <p>Sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.<br><br></p>
            <h2 class="text-dark">Wisi malesuada scelerisque praesent mi accumsan</h2>
            <p>Tortor massa nec orci accusamus auctor aute euismod lacus ipsam culpa earum beatae fugiat. Wisi malesuada scelerisque praesent mi accumsan euismod ea penatibus felis lacinia maiores dolorum optio officia. Nonummy libero adipiscing vel nulla dis tristique torquent sollicitudin felis inceptos eligendi molestiae omnis aspernatur.<p>
          </div>
          
          <!-- Image-->
          <img class="l-6 hide-s hide-m" src="{% static 'img/img-01.jpg' %}">
        </section>
        
        <!-- SECTION 2 -->
        <section class="grid margin margin-bottom padding-2x background-primary">
          <div class="s-12 m-6 l-3">
            <span class="timer text-size-50 text-white text-strong">1500</span>
            <h3 class="text-uppercase text-strong">Ultricies eros sociis</h3>
            <p class="text-size-16 margin-m-bottom-20">Eodem modo typi nonummy maecenas ultricies eros sociis hendrerit dictum.</p> 
          </div>

          <div class="s-12 m-6 l-3">
            <span class="timer text-size-50 text-white text-strong">95</span> <span class="text-size-50 text-white text-strong">%</span>
            <h3 class="text-uppercase text-strong">Magna condimentum suspendisse</h3>
            <p class="text-size-16 margin-m-bottom-20">Duis autem libero ullam magna condimentum suspendisse pellentesque.</p> 
          </div>

          <div class="s-12 m-6 l-3">
            <span class="timer text-size-50 text-white text-strong">287</span>
            <h3 class="text-uppercase text-strong">Consequat phasellus orci</h3>
            <p class="text-size-16 margin-m-bottom-20">Mirum est notare dolor consequat phasellus orci pellentesque hendrerit.</p> 
          </div>

          <div class="s-12 m-6 l-3">
            <span class="timer text-size-50 text-white text-strong">7</span> <span class="text-size-50 text-white text-strong">milion</span>
            <h3 class="text-uppercase text-strong">Augue et venenatis</h3>
            <p class="text-size-16 margin-m-bottom-20">Nam liber tempor erat augue et venenatis lorem ipsum dolor si amet.</p> 
          </div>
        </section>
        
        <!-- SECTION 3 -->
        <section class="grid margin">
          <h2 class="s-12 text-white text-thin text-size-30 text-white text-uppercase margin-top-bottom-20 center text-center">Our <b>Dream Team</b></h2> 
          <div class="s-12 m-6 l-2 margin-bottom">
            <img src="{% static 'img/team-01.jpg' %}"/>
            <h4 class="background-primary padding text-strong">Frank Star</h4>
            <p class="margin-bottom-10 text-primary text-uppercase">Boss</p>                                                                                                                                          
          </div>
          <div class="s-12 m-6 l-2 margin-bottom">
            <img src="{% static 'img/team-02.jpg' %}"/>
            <h4 class="background-primary padding text-strong">Jane Naismith</h4>
            <p class="margin-bottom-10 text-primary text-uppercase">Graphic Designer</p>                                                                                                                                          
          </div>
          <div class="s-12 m-6 l-2 margin-bottom"> 
            <img src="{% static 'img/team-03.jpg' %}"/>
            <h4 class="background-primary padding text-strong">Mark Stoner</h4>
            <p class="margin-bottom-10 text-primary text-uppercase">Web Designer</p>                                                                                                                                          
          </div>
          <div class="s-12 m-6 l-2 margin-bottom"> 
            <img src="{% static 'img/team-04.jpg' %}"/>
            <h4 class="background-primary padding text-strong">Steve Carpenter</h4>
            <p class="margin-bottom-10 text-primary text-uppercase">Web Developer</p>                                                                                                                                          
          </div>
          <div class="s-12 m-6 l-2 margin-bottom"> 
            <img src="{% static 'img/team-05.jpg' %}"/>
            <h4 class="background-primary padding text-strong">Steff Kingston</h4>
            <p class="margin-bottom-10 text-primary text-uppercase">Account Manager</p>                                                                                                                                          
          </div>
          <div class="s-12 m-6 l-2 margin-bottom"> 
            <img src="{% static 'img/team-06.jpg' %}"/>
            <h4 class="background-primary padding text-strong">John Sandman</h4>
            <p class="margin-bottom-10 text-primary text-uppercase">Account Manager</p>                                                                                                                                          
          </div>   
        </section>
                 
      </main>
      
       
      <!-- FOOTER -->
      <footer class="grid">
        <!-- Footer - top -->
        <!-- Image-->
        <div class="s-12 l-3 m-row-3 margin-bottom background-image" style="background-image:url(img/img-04.jpg)"></div>
        
        <div class="s-12 m-9 l-3 padding-2x margin-bottom background-dark">
           <h2 class="text-strong text-uppercase">Who We Are?</h2>
           <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy.</p>
        </div>
        
        <div class="s-12 m-9 l-3 padding-2x margin-bottom background-dark">
           <h2 class="text-strong text-uppercase">Where We Are?</h2>
           <img class="full-img" src="{% static 'img/map.svg' %}" alt=""/>
        </div>
        
        <div class="s-12 m-9 l-3 padding-2x margin-bottom background-dark">
           <h2 class="text-strong text-uppercase">Contact Us</h2>
           <p><b class="text-primary margin-right-10">P</b> 0800 4521 800 50</p>
           <p><b class="text-primary margin-right-10">M</b> <a class="text-primary-hover" href="mailto:contact@sampledomain.com">contact@sampledomain.com</a></p>
           <p><b class="text-primary margin-right-10">M</b> <a class="text-primary-hover" href="mailto:office@sampledomain.com">office@sampledomain.com</a></p>
        </div>
        
        <!-- Footer - bottom -->
        <div class="s-12 text-center margin-bottom">
          <p class="text-size-12">Copyright 2019, Vision Design - graphic zoo</p>
          <p class="text-size-12">All images have been purchased from Bigstock. Do not use the images in your website.</p>
          <p><a class="text-size-12 text-primary-hover" href="http://www.myresponsee.com" title="Responsee - lightweight responsive framework">Design and coding by Responsee Team</a></p>
        </div>
      </footer>                                                                    
      <script type="text/javascript" src="{% static 'js/responsee.js' %}"></script>
      <script type="text/javascript" src="{% static 'owl-carousel/owl.carousel.js' %}"></script>
      <script type="text/javascript" src="{% static 'js/template-scripts.js' %}"></script>

   </body>
</html>

templates/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en-US">
 <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Free responsive business website template</title>
    <link rel="stylesheet" href="{% static 'css/components.css' %}">
    <link rel="stylesheet" href="{% static 'css/icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsee.css' %}">
    <link rel="stylesheet" href="{% static 'owl-carousel/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'owl-carousel/owl.theme.css' %}">
    <!-- CUSTOM STYLE -->      
    <link rel="stylesheet" href="{% static 'css/template-style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Barlow:100,300,400,700,800&amp;subset=latin-ext" rel="stylesheet">  
    <script type="text/javascript" src="{% static 'js/jquery-1.8.3.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>    
 </head>

 <!--
  You can change the color scheme of the page. Just change the class of the <body> tag. 
  You can use this class: "primary-color-white", "primary-color-red", "primary-color-orange", "primary-color-blue", "primary-color-aqua", "primary-color-dark" 
  -->
  
  <!--
  Each element is able to have its own background or text color. Just change the class of the element.  
  You can use this class: 
  "background-white", "background-red", "background-orange", "background-blue", "background-aqua", "background-primary" 
  "text-white", "text-red", "text-orange", "text-blue", "text-aqua", "text-primary"
  -->

 <body class="size-1520 primary-color-red background-dark">
    <!-- HEADER -->
    <header class="grid">
      <!-- Top Navigation -->
      <nav class="s-12 grid background-none background-primary-hightlight">
         <!-- logo -->
         <a href="/" class="m-12 l-3 padding-2x logo">
            <img src="{% static 'img/logo.svg' %}">
         </a>
         <div class="top-nav s-12 l-9"> 
            <ul class="top-ul right chevron">
              <li><a href="{% url 'bir:home_page' %}">Home</a></li>
              <li><a href="{% url 'bir:about_page' %}">About Us</a></li>
              <li><a href="{% url 'bir:services_page' %}">Services</a></li>
              <li><a href="{% url 'bir:gallery_page' %}">Gallery</a></li>
              <li><a href="{% url 'bir:contact_page' %}">Contact</a></li>
            </ul>
         </div>
      </nav>
    </header>
      
      <!-- MAIN -->
      <main role="main">
        <!-- TOP SECTION -->
        <header class="grid">
        	<div class="s-12 padding-2x">
            <h1 class="text-strong text-white text-center center text-size-60 text-uppercase margin-bottom-20">Contact Us</h1>
          </div>
        </header>
        
        <!-- SECTION 1 -->
        <section class="grid margin-bottom-20">
          <div class="m-12 l-7 center">
            <!-- Contact Information-->
            <div class="s-12 padding-2x background-white text-center">                  
              <h2 class="text-size-20 margin-bottom-10 text-strong text-uppercase text-dark">Company Address</h2>                
              <p>Aviation Way 99</p>
              <p>Los Angeles, USA</p>             

              <h2 class="text-size-20 margin-top-30 margin-bottom-10 text-strong text-uppercase text-dark">E-mail</h2>                
              <p><a class="text-primary-hover" href="mailto:contact@sampledomain.com">contact@sampledomain.com</a></p>
              <p><a class="text-primary-hover" href="mailto:office@sampledomain.com">office@sampledomain.com</a></p>               

              <h2 class="text-size-20 margin-top-30 margin-bottom-10 text-strong text-uppercase text-dark">Phone Numbers</h2>                
              <p>0800 4521 800 50</p>
              <p>0450 5896 625 16</p>
              <p>0798 6546 465 </p>               
            </div>

            <iframe class="s-12 center" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d408353.5714751251!2d-118.71693940358037!3d33.79914670853249!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80c2b4655ccd2001%3A0xa7f54b3bb5afde44!2s99+Aviation+Blvd%2C+Manhattan+Beach%2C+CA+90266%2C+Spojen%C3%A9+%C5%A1t%C3%A1ty+americk%C3%A9!5e0!3m2!1ssk!2ssk!4v1558635197012!5m2!1ssk!2ssk" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>  
          </div>                  

        </section>
      </main>
      
       
      <!-- FOOTER -->
      <footer class="grid">
        <!-- Footer - top -->
        <!-- Image-->
        <div class="s-12 l-3 m-row-3 margin-bottom background-image" style="background-image:url(img/img-04.jpg)"></div>
        
        <div class="s-12 m-9 l-3 padding-2x margin-bottom background-dark">
           <h2 class="text-strong text-uppercase">Who We Are?</h2>
           <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy.</p>
        </div>
        
        <div class="s-12 m-9 l-3 padding-2x margin-bottom background-dark">
           <h2 class="text-strong text-uppercase">Where We Are?</h2>
           <img class="full-img" src="{% static 'img/map.svg' %}" alt=""/>
        </div>
        
        <div class="s-12 m-9 l-3 padding-2x margin-bottom background-dark">
           <h2 class="text-strong text-uppercase">Contact Us</h2>
           <p><b class="text-primary margin-right-10">P</b> 0800 4521 800 50</p>
           <p><b class="text-primary margin-right-10">M</b> <a class="text-primary-hover" href="mailto:contact@sampledomain.com">contact@sampledomain.com</a></p>
           <p><b class="text-primary margin-right-10">M</b> <a class="text-primary-hover" href="mailto:office@sampledomain.com">office@sampledomain.com</a></p>
        </div>
        
        <!-- Footer - bottom -->
        <div class="s-12 text-center margin-bottom">
          <p class="text-size-12">Copyright 2019, Vision Design - graphic zoo</p>
          <p class="text-size-12">All images have been purchased from Bigstock. Do not use the images in your website.</p>
          <p><a class="text-size-12 text-primary-hover" href="http://www.myresponsee.com" title="Responsee - lightweight responsive framework">Design and coding by Responsee Team</a></p>
        </div>
      </footer>      
      <script type="text/javascript" src="{% static 'js/responsee.js' %}"></script>
      <script type="text/javascript" src="{% static 'owl-carousel/owl.carousel.js' %}"></script>
      <script type="text/javascript" src="{% static 'js/template-scripts.js' %}"></script>
      
   </body>
</html>

templates/gallery.html
{% load static %}
<!DOCTYPE html>
<html lang="en-US">
   <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>Free responsive business website template</title>
      <link rel="stylesheet" href="{% static 'css/components.css' %}">
      <link rel="stylesheet" href="{% static 'css/icons.css' %}">
      <link rel="stylesheet" href="{% static 'css/responsee.css' %}">
      <link rel="stylesheet" href="{% static 'owl-carousel/owl.carousel.css' %}">
      <link rel="stylesheet" href="{% static 'owl-carousel/owl.theme.css' %}">
      <!-- CUSTOM STYLE -->      
      <link rel="stylesheet" href="{% static 'css/template-style.css' %}">
      <link href="https://fonts.googleapis.com/css?family=Barlow:100,300,400,700,800&amp;subset=latin-ext" rel="stylesheet">  
      <script type="text/javascript" src="{% static 'js/jquery-1.8.3.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>    
   </head>

   <!--
    You can change the color scheme of the page. Just change the class of the <body> tag. 
    You can use this class: "primary-color-white", "primary-color-red", "primary-color-orange", "primary-color-blue", "primary-color-aqua", "primary-color-dark" 
    -->
    
    <!--
    Each element is able to have its own background or text color. Just change the class of the element.  
    You can use this class: 
    "background-white", "background-red", "background-orange", "background-blue", "background-aqua", "background-primary" 
    "text-white", "text-red", "text-orange", "text-blue", "text-aqua", "text-primary"
    -->

   <body class="size-1520 primary-color-red background-dark">
      <!-- HEADER -->
      <header class="grid">
        <!-- Top Navigation -->
        <nav class="s-12 grid background-none background-primary-hightlight">
           <!-- logo -->
           <a href="/" class="m-12 l-3 padding-2x logo">
              <img src="{% static 'img/logo.svg' %}">
           </a>
           <div class="top-nav s-12 l-9"> 
              <ul class="top-ul right chevron">
                <li><a href="{% url 'bir:home_page' %}">Home</a></li>
                <li><a href="{% url 'bir:about_page' %}">About Us</a></li>
                <li><a href="{% url 'bir:services_page' %}">Services</a></li>
                <li><a href="{% url 'bir:gallery_page' %}">Gallery</a></li>
                <li><a href="{% url 'bir:contact_page' %}">Contact</a></li>
              </ul>
           </div>
        </nav>
      </header>
      
      <!-- MAIN -->
      <main role="main">
        <!-- TOP SECTION -->
        <header class="grid">
        	<div class="s-12 padding-2x">
            <h1 class="text-strong text-white text-center center text-size-60 text-uppercase margin-bottom-20">Our References</h1>
            <p class="text-size-20 text-white text-center center text-uppercase">Con nonummy sem integer interdum volutpat dis eget eligendi aliquip dolorum magnam. Iriure duis autem vel<br> eum dolor in hendrerit in vulputate velit esse molestie consequat.</p>
          </div>
        </header>
      
        <section class="grid margin">
          <img class="s-12 m-6 margin-bottom" src="{% static 'img/portfolio/thumb-01.jpg' %}" alt=""/>
          <img class="s-12 m-6 margin-bottom" src="{% static 'img/portfolio/thumb-02.jpg' %}" alt=""/>
          <img class="s-12 m-6 margin-bottom" src="{% static 'img/portfolio/thumb-03.jpg' %}" alt=""/>
          <img class="s-12 m-6 margin-bottom" src="{% static 'img/portfolio/thumb-04.jpg' %}" alt=""/>
          <img class="s-12 m-6 margin-bottom" src="{% static 'img/portfolio/thumb-05.jpg' %}" alt=""/>
          <img class="s-12 m-6 margin-bottom" src="{% static 'img/portfolio/thumb-06.jpg' %}" alt=""/>
          <img class="s-12 m-6 margin-bottom" src="{% static 'img/portfolio/thumb-07.jpg' %}" alt=""/>
          <img class="s-12 m-6 margin-bottom" src="{% static 'img/portfolio/thumb-08.jpg' %}" alt=""/>
        </section>
        
      </main>
      
       
      <!-- FOOTER -->
      <footer class="grid">
        <!-- Footer - top -->
        <!-- Image-->
        <div class="s-12 l-3 m-row-3 margin-bottom background-image" style="background-image:url(img/img-04.jpg)"></div>
        
        <div class="s-12 m-9 l-3 padding-2x margin-bottom background-dark">
           <h2 class="text-strong text-uppercase">Who We Are?</h2>
           <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy.</p>
        </div>
        
        <div class="s-12 m-9 l-3 padding-2x margin-bottom background-dark">
           <h2 class="text-strong text-uppercase">Where We Are?</h2>
           <img class="full-img" src="{% static 'img/map.svg' %}" alt=""/>
        </div>
        
        <div class="s-12 m-9 l-3 padding-2x margin-bottom background-dark">
           <h2 class="text-strong text-uppercase">Contact Us</h2>
           <p><b class="text-primary margin-right-10">P</b> 0800 4521 800 50</p>
           <p><b class="text-primary margin-right-10">M</b> <a class="text-primary-hover" href="mailto:contact@sampledomain.com">contact@sampledomain.com</a></p>
           <p><b class="text-primary margin-right-10">M</b> <a class="text-primary-hover" href="mailto:office@sampledomain.com">office@sampledomain.com</a></p>
        </div>
        
        <!-- Footer - bottom -->
        <div class="s-12 text-center margin-bottom">
          <p class="text-size-12">Copyright 2019, Vision Design - graphic zoo</p>
          <p class="text-size-12">All images have been purchased from Bigstock. Do not use the images in your website.</p>
          <p><a class="text-size-12 text-primary-hover" href="http://www.myresponsee.com" title="Responsee - lightweight responsive framework">Design and coding by Responsee Team</a></p>
        </div>
      </footer>                                                                    
      <script type="text/javascript" src="{% static 'js/responsee.js' %}"></script>
      <script type="text/javascript" src="{% static 'owl-carousel/owl.carousel.js' %}"></script>
      <script type="text/javascript" src="{% static 'js/template-scripts.js' %}"></script>

   </body>
</html>